export const textToImg ={
    day:{
        "多云":"./images/day/yin.png",
        "晴":"./images/day/qing.png",
        "阴":"./images/day/yun.png",
        "雨":"./images/day/yu.png",
        "日出":"./images/rise.png",
        "日落":"./images/set.png",
        
    },
    night:{
        "多云":"./images/night/yin.png",
        "晴":"./images/night/qing.png",
        "阴":"./images/night/yun.png",
        "雨":"./images/night/yu.png",
        "日出":"./images/rise.png",
        "日落":"./images/set.png",
    },
    indicate:{
        2:"./images/washcar.png",
        15:"./images/bus.png",
        3:"./images/cloth.png",
        9:"./images/cold.png",
        4:"./images/diaoyu.png",
        14:"./images/liangshai.png",
        6:"./images/lvyou.png",
        1:"./images/sports.png"
    }
}